apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microbot
  name: microbot
spec:
  replicas: 10
  selector:
    matchLabels:
      app: microbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microbot
    spec:
      containers:
      - image: dontrebootme/microbot:v1
        imagePullPolicy: ""
        name: microbot
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 30
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
